baseURL = "https://werkstattcodes.netlify.com/"
title = "werk.statt.codes"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-149910232-1"
enableEmoji = true 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "© Roland Schmidt <a href='https://twitter.com/zoowalk' style='color:gray'>@zoowalk</a>"
description = "Playground with R"

[taxonomies]
  tag = "tags"
  about = "about"

[params]
  twitter = "zoowalk"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "/blog"
  url = "/post/"

[[params.menu]]
  name = "/tags"
  url = "/tags/"
  
[[params.menu]]
  name = "/about"
  url = "/about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true