---
title: new post with rmd
author: rs
date: '2019-10-10'
slug: new-post-with-rmd
categories:
  - rmd
tags: []
description: ''
---
hello

## Context
Here's another quick post on the results of the recent general elections in Austria. It goes without saying that there has been already a flurry of analyses, visualisations etc on it and there is hardly much new to add. Nevertheless, below a few 


```{r remedy001}

library(tidyverse)

```


```{r, eval=F}
nrw19_imp <- readr::read_csv2(file = file,
                              locale=locale(encoding="latin1")) %>% 
  janitor::remove_empty(., which=c("cols")) %>% 
  janitor::clean_names() %>% 
  rename(gkz=x1)

nrw19 <- nrw19_imp %>%
  filter(str_detect(gkz, "00$|99$")) %>% 
  filter(!str_detect(gkz, ".{2}[A-Z].*")) %>%  #remove aggregates of regional electoral districts
  filter(!str_detect(gkz, "0000$")) %>%  #remove state level electoral districts
  filter(!str_detect(gkz, ".{2}0099")) %>%    #remove state level electoral districts
  mutate(district_id=stringr::str_sub(gkz, start=1, end=4))
```

# another heading 1
text

## a heading 2
text
### a heading 3
text
# a heading 1
text
## a heading 2
text