---
title: 'Austrian Parliament: MPs transparency and conflict of interest report - Bundesrat'
author: rs
date: '2020-07-22'
slug: austrian-parliament-mps-transparency-and-conflict-of-interest-report-bundesrat
categories: []
draft: true
tags:
  - Austria
  - OCR
description: ''
---

# Context

This is a follow-up on my previous post on the transprancey report by Austria's Parliament. While I limited 


# Steps in R

## Setup
<details closed> 
<summary>Code: Load packages</summary> 
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(extrafont)
loadfonts(device = "win", quiet = T)
library(hrbrthemes)
hrbrthemes::update_geom_font_defaults(family = "Roboto Condensed",
                                      size=3)
library(scales)
library(knitr)
library(paletteer)
library(ggtext)
library(glue)
library(gt)
library(DT)
library(pdftools)
library(lemon)
library(gender)
library(ggiraph)

```
</details>

<details closed> 
<summary>Code: Define rmarkdown options</summary> 
```{r setup, echo = T}
knit_hooks$set(wrap = function(before, options, envir) {
  if (before) {
    paste0("<", options$wrap, ">")
  } else {
    paste0("</", options$wrap, ">")
  }
})

knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = "left",
  # fig.height = 5,
  # fig.width = 7,
  out.width = "100%",
  message = FALSE,
  warning = FALSE,
  dpi = 300
)

options(width = 180, dplyr.width = 150)
```
</details>

<details closed> 
<summary>Code: Define plot theme</summary> 
```{r echo=TRUE}
theme_post <- function() {
  hrbrthemes::theme_ipsum_rc() +
    theme(
      plot.margin = margin(l = 0, unit = "cm"),
      plot.title = element_markdown(
        color = "grey20",
        face = "bold",
        margin = margin(l = 0, unit = "cm"),
        size = 13
      ),
      plot.title.position = "plot",
      plot.subtitle = element_text(
        color = "grey50",
        margin = margin(t = 0.2, b = 0.3, unit = "cm"),
        size = 11
      ),
      plot.caption = element_text(
        color = "grey50",
        size = 8,
        hjust = c(0)
      ),
      plot.caption.position = "panel",
      axis.title.x = element_text(angle = 0,
                                         color="grey50",
                                         hjust=1),
      axis.text.x = element_text(size = 9, 
                                 color = "grey50"),
      axis.title.y = element_blank(),
      axis.text.y = element_text(size = 9,
                                 color="grey50"),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.spacing = unit(0.25, "cm"),
      panel.spacing.y = unit(0.25, "cm"),
      strip.text = element_text(
        angle = 0,
        size = 9,
        vjust = 1,
        face = "bold"
      ),
      legend.title = element_text(
        color = "grey30",
        face = "bold",
        vjust = 1,
        size = 7
      ),
      legend.text = element_text(
        size = 7,
        color = "grey30"
      ),
      legend.justification = "left",
      legend.box = "horizontal", # arrangement of multiple legends
      legend.direction = "vertical",
      legend.margin = margin(l = 0, t = 0, unit = "cm"),
      legend.spacing.y = unit(0.07, units = "cm"),
      legend.text.align = 0,
      legend.box.just = "top",
      legend.key.height = unit(0.2, "line"),
      legend.key.width = unit(0.5, "line"),
      text = element_text(size = 5)
    )
}

my_caption=c("data: Austrian Parliament, Liste gemäß § 9 Bezügebegrenzungs-BVG, 2020. \nanalysis: Roland Schmidt | @zoowalk | https://werk.statt.codes")
```
</details>

## Data extraction

<details open> 
<summary>Code: Extract text from pdfs </summary> 
```{r}
my_path <- here::here("blog_data", "MP_activities", "BezBegrBVGPar9-BR.pdf")

df_data <- pdftools::pdf_data(pdf=my_path)

df1 <- df_data %>% 
  map_dfr(., bind_rows, .id="id") %>% 
  mutate(id=as.numeric(id)) 

df_names <- df1 %>% 
  filter(y==99) %>% 
  group_by(id) %>% 
  summarize(name=paste0(text, collapse=" "))

df2 <- df1 %>% 
  group_by(id) %>% 
  mutate(line_diff = y - dplyr::lag(y, default = 0)) %>%
    mutate(row_jump = case_when(
      line_diff > 11 ~ 1,
      TRUE ~ 0
    )) %>%
  mutate(row_indicator = cumsum(row_jump)) %>%
  group_by(id, row_indicator) %>% 
  summarise(text=paste0(text, collapse=" ")) 
  
df_income <- df2 %>% 
  filter(str_detect(text, regex("2019\\:"))==T) %>% 
  mutate(income=str_extract(text, "(?<=2019:.?)\\S")) %>% 
  select(-row_indicator, -text)

df_all <- df_names %>% 
  left_join(., df_income,
            by="id") %>% 
      mutate(name_clean=name %>% str_remove(., regex(",.*$")) %>% 
           str_remove_all(., regex("\\S*\\.")) %>% 
           str_remove_all(., regex("\\(.*\\)")) %>% 
           str_trim()) %>% 
    mutate(first_name=str_extract(name_clean, regex("^\\S*"))) 

df_all <- df_all %>%
  mutate(name_gender=map(first_name, possibly(gender,  otherwise="missing")))  

df_all <- df_all %>% 
  mutate(gender=map_chr(name_gender, purrr::pluck, "gender", .default=NA)) %>% 
  select(-name_gender)

```
</details>

```{r}
library(rvest)
#link from button 'alle anzeigen'
link_br_all <- "https://www.parlament.gv.at/WWER/BR/MITGL/index.shtml?xdocumentUri=&GP=ALLE&BL=ALLE_BL&STEP=1070&feldRnr=3&FR=ALLE&M=M&ascDesc=ASC&NRBR=BR&FBEZ=FW_007&view=&jsMode=&LISTE=&requestId=870460213E&W=W&letter=&WP=ALLE&R_WF=WP&listeId=7&filterJq="

df_table <- link_br_all %>%
  read_html() %>% 
  html_nodes("#filterListeFW_007 > table") %>% 
  html_table() %>% .[[1]]

df_br <- df_table %>% 
  janitor::clean_names() %>% 
  mutate(name=str_remove_all(name, "Name") %>% str_trim() %>% str_squish(),
         wahlpartei=str_remove_all(wahlpartei, "Wahlpartei") %>% str_trim() %>% str_squish(),
         gesetzgebungsperioden_des_nr=str_remove_all(gesetzgebungsperioden_des_nr, "Gesetzgebungsperioden des NR") %>% 
           str_trim() %>% str_squish(),
         bundesland=str_remove_all(bundesland, "Bundesland") %>% str_trim() %>% str_squish()) %>% 
  select(-bereich)


df_all_x <- df_all %>% 
  left_join(., df_br,
            by="name")
```



# Results

